module.exports = {
    role: {
        ROLE_USER: 'USER',
        ROLE_SUPER_ADMIN: 'SUPER_ADMIN',
        ROLE_ADMIN: 'ADMIN',
    },
    permission: {
        PERMISSION_CREATE_AERA: "PERMISSION_CREATE_AERA",
        PERMISSION_UPDATE_AERA: "PERMISSION_UPDATE_AERA",
        PERMISSION_DELETE_AERA: "PERMISSION_DELETE_AERA",
        PERMISSION_READ_AERA: "PERMISSION_READ_AERA",

        PERMISSION_CREATE_UNIT: "PERMISSION_CREATE_UNIT",
        PERMISSION_UPDATE_UNIT: "PERMISSION_UPDATE_UNIT",
        PERMISSION_DELETE_UNIT: "PERMISSION_DELETE_UNIT",
        PERMISSION_READ_UNIT: "PERMISSION_READ_UNIT",

        PERMISSION_CREATE_ROLE: "PERMISSION_CREATE_ROLE",
        PERMISSION_UPDATE_ROLE: "PERMISSION_UPDATE_ROLE",
        PERMISSION_DELETE_ROLE: "PERMISSION_DELETE_ROLE",
        PERMISSION_READ_ROLE: "PERMISSION_READ_ROLE",



    },
    stateDevice: {
        DEVICE_ERROR: 0,
        DEVICE_LOCK: 1,
        DEVICE_SUCCESS: 2,
    }


}